import { db, usersTable, listingsTable, bookingsTable, reviewsTable } from "@workspace/db";
import { sql } from "drizzle-orm";

async function seed() {
  console.log("Clearing existing data...");
  await db.execute(sql`TRUNCATE reviews, bookings, favorites, listings, users RESTART IDENTITY CASCADE`);

  console.log("Seeding users...");
  const [rahul, priya, arjun, neha, vikram] = await db.insert(usersTable).values([
    {
      name: "Rahul Sharma",
      email: "rahul@example.com",
      phone: "+91 98765 43210",
      role: "both",
      bio: "Property owner in Mumbai with 3 parking spots near BKC.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=rahul",
      vehicleType: "Sedan",
      vehiclePlate: "MH01 AB 1234",
    },
    {
      name: "Priya Mehta",
      email: "priya@example.com",
      phone: "+91 87654 32109",
      role: "host",
      bio: "Bangalore host with covered spots near Koramangala.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya",
    },
    {
      name: "Arjun Nair",
      email: "arjun@example.com",
      phone: "+91 76543 21098",
      role: "driver",
      bio: "Frequent traveller between Mumbai and Pune.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=arjun",
      vehicleType: "SUV/MUV",
      vehiclePlate: "MH12 CD 5678",
    },
    {
      name: "Neha Gupta",
      email: "neha@example.com",
      phone: "+91 65432 10987",
      role: "both",
      bio: "Delhi homeowner with a secure covered garage.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=neha",
      vehicleType: "Hatchback",
      vehiclePlate: "DL05 EF 9012",
    },
    {
      name: "Vikram Singh",
      email: "vikram@example.com",
      phone: "+91 54321 09876",
      role: "host",
      bio: "Commercial property manager in Hyderabad, offering premium parking near Hitech City.",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=vikram",
    },
  ]).returning();

  console.log("Seeding listings...");
  const listings = await db.insert(listingsTable).values([
    // Mumbai
    {
      hostId: rahul.id,
      title: "Covered Spot near BKC Metro Station",
      description: "Secure covered parking right next to the BKC metro exit. Perfect for office-goers. 24/7 CCTV, clean facility, no hassle entry with QR code. Walking distance to major corporates.",
      address: "Plot C-68, Bandra Kurla Complex",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      latitude: "19.0596",
      longitude: "72.8656",
      hourlyRate: "120",
      dailyRate: "700",
      monthlyRate: "9000",
      pricingType: "all",
      totalSpots: 3,
      availableSpots: 2,
      vehicleTypes: JSON.stringify(["Sedan", "SUV/MUV", "Hatchback"]),
      amenities: JSON.stringify(["Covered", "Security Camera", "Gated", "24/7 Access", "Lighting"]),
      photos: JSON.stringify([
        "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800&q=80",
        "https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800&q=80",
      ]),
      isActive: true,
      rating: "4.8",
      reviewCount: 24,
    },
    {
      hostId: rahul.id,
      title: "Basement Parking - Andheri West",
      description: "Private basement spot in a residential complex near Andheri station. Safe, gated entry. Ideal for daily commuters. EV charging available. Contact for monthly discounts.",
      address: "Lokhandwala Complex, Andheri West",
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      latitude: "19.1364",
      longitude: "72.8296",
      hourlyRate: "80",
      dailyRate: "500",
      monthlyRate: "7000",
      pricingType: "all",
      totalSpots: 1,
      availableSpots: 1,
      vehicleTypes: JSON.stringify(["Two-Wheeler", "Hatchback", "Sedan"]),
      amenities: JSON.stringify(["Covered", "Security Camera", "EV Charging", "Gated"]),
      photos: JSON.stringify([
        "https://images.unsplash.com/photo-1486006920555-c77dcf18193c?w=800&q=80",
        "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?w=800&q=80",
      ]),
      isActive: true,
      rating: "4.6",
      reviewCount: 18,
    },
    // Delhi
    {
      hostId: neha.id,
      title: "Secure Garage near Connaught Place",
      description: "Private covered garage 5 min walk from CP Metro. Excellent lighting, security guard on duty 8am-10pm. Perfect for tourists and office workers visiting Central Delhi.",
      address: "K-Block, Connaught Place, New Delhi",
      city: "Delhi",
      state: "Delhi",
      country: "India",
      latitude: "28.6315",
      longitude: "77.2167",
      hourlyRate: "100",
      dailyRate: "600",
      monthlyRate: "8500",
      pricingType: "all",
      totalSpots: 2,
      availableSpots: 1,
      vehicleTypes: JSON.stringify(["Sedan", "SUV/MUV", "Hatchback"]),
      amenities: JSON.stringify(["Covered", "Security Camera", "Lighting", "24/7 Access"]),
      photos: JSON.stringify([
        "https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800&q=80",
        "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800&q=80",
      ]),
      isActive: true,
      rating: "4.7",
      reviewCount: 31,
    },
    {
      hostId: neha.id,
      title: "Open Lot - Dwarka Sector 12",
      description: "Spacious open parking lot in Dwarka. Very affordable daily and monthly rates. Great for long-term parking. 10 min from Dwarka Metro on Blue Line.",
      address: "Sector 12, Dwarka",
      city: "Delhi",
      state: "Delhi",
      country: "India",
      latitude: "28.5921",
      longitude: "77.0460",
      hourlyRate: "40",
      dailyRate: "200",
      monthlyRate: "3500",
      pricingType: "all",
      totalSpots: 10,
      availableSpots: 7,
      vehicleTypes: JSON.stringify(["Two-Wheeler", "Hatchback", "Sedan", "SUV/MUV", "Truck/Tempo"]),
      amenities: JSON.stringify(["Security Camera", "Lighting"]),
      photos: JSON.stringify([
        "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80",
      ]),
      isActive: true,
      rating: "4.3",
      reviewCount: 12,
    },
    // Bangalore
    {
      hostId: priya.id,
      title: "Covered Spot - Koramangala 5th Block",
      description: "Premium covered parking in the heart of Koramangala. Walking distance to startups, restaurants, and Forum mall. Perfect for tech professionals working in the area.",
      address: "5th Block, Koramangala",
      city: "Bangalore",
      state: "Karnataka",
      country: "India",
      latitude: "12.9352",
      longitude: "77.6245",
      hourlyRate: "90",
      dailyRate: "550",
      monthlyRate: "7500",
      pricingType: "all",
      totalSpots: 2,
      availableSpots: 2,
      vehicleTypes: JSON.stringify(["Two-Wheeler", "Sedan", "Hatchback", "SUV/MUV"]),
      amenities: JSON.stringify(["Covered", "Security Camera", "EV Charging", "24/7 Access"]),
      photos: JSON.stringify([
        "https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=800&q=80",
        "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800&q=80",
      ]),
      isActive: true,
      rating: "4.9",
      reviewCount: 42,
    },
    {
      hostId: priya.id,
      title: "Gated Parking - Indiranagar 100ft Road",
      description: "Premium gated spot near 100ft road. Close to CMH Road restaurants and pubs. Well lit, CCTV monitored. Great for evening/weekend visitors to Indiranagar.",
      address: "100 Feet Road, Indiranagar",
      city: "Bangalore",
      state: "Karnataka",
      country: "India",
      latitude: "12.9784",
      longitude: "77.6408",
      hourlyRate: "70",
      dailyRate: "400",
      monthlyRate: "6000",
      pricingType: "all",
      totalSpots: 4,
      availableSpots: 3,
      vehicleTypes: JSON.stringify(["Two-Wheeler", "Hatchback", "Sedan"]),
      amenities: JSON.stringify(["Gated", "Security Camera", "Lighting"]),
      photos: JSON.stringify([
        "https://images.unsplash.com/photo-1486006920555-c77dcf18193c?w=800&q=80",
      ]),
      isActive: true,
      rating: "4.5",
      reviewCount: 19,
    },
    // Pune
    {
      hostId: rahul.id,
      title: "Private Spot - Koregaon Park",
      description: "Exclusive parking spot in Koregaon Park near the famous cafes and German Bakery area. Perfect for weekend brunch or evening plans. Very secure residential complex.",
      address: "Lane 7, Koregaon Park",
      city: "Pune",
      state: "Maharashtra",
      country: "India",
      latitude: "18.5362",
      longitude: "73.8938",
      hourlyRate: "60",
      dailyRate: "350",
      monthlyRate: "5500",
      pricingType: "all",
      totalSpots: 1,
      availableSpots: 1,
      vehicleTypes: JSON.stringify(["Hatchback", "Sedan", "SUV/MUV"]),
      amenities: JSON.stringify(["Covered", "Security Camera", "Gated"]),
      photos: JSON.stringify([
        "https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?w=800&q=80",
      ]),
      isActive: true,
      rating: "4.7",
      reviewCount: 9,
    },
    // Hyderabad
    {
      hostId: vikram.id,
      title: "Commercial Parking Hub - Hitech City",
      description: "Professional parking facility near Hitech City IT corridor. Serving major tech park employees and visitors. Multi-level, covered, with dedicated two-wheeler zone.",
      address: "Mindspace, Hitech City",
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
      latitude: "17.4435",
      longitude: "78.3772",
      hourlyRate: "50",
      dailyRate: "300",
      monthlyRate: "4500",
      pricingType: "all",
      totalSpots: 20,
      availableSpots: 12,
      vehicleTypes: JSON.stringify(["Two-Wheeler", "Hatchback", "Sedan", "SUV/MUV"]),
      amenities: JSON.stringify(["Covered", "Security Camera", "Gated", "24/7 Access", "Lighting", "EV Charging"]),
      photos: JSON.stringify([
        "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80",
        "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800&q=80",
      ]),
      isActive: true,
      rating: "4.6",
      reviewCount: 56,
    },
  ]).returning();

  console.log("Seeding bookings...");
  await db.insert(bookingsTable).values([
    {
      listingId: listings[0].id,
      driverId: arjun.id,
      hostId: rahul.id,
      startDate: new Date("2026-05-15T09:00:00"),
      endDate: new Date("2026-05-15T18:00:00"),
      pricingType: "hourly",
      totalPrice: "1080",
      status: "confirmed",
      qrCode: `PARKBNB-${listings[0].id}-1715760000`,
      vehicleType: "SUV/MUV",
      vehiclePlate: "MH12 CD 5678",
    },
    {
      listingId: listings[2].id,
      driverId: arjun.id,
      hostId: neha.id,
      startDate: new Date("2026-05-20T10:00:00"),
      endDate: new Date("2026-05-21T10:00:00"),
      pricingType: "daily",
      totalPrice: "600",
      status: "confirmed",
      qrCode: `PARKBNB-${listings[2].id}-1716192000`,
      vehicleType: "SUV/MUV",
      vehiclePlate: "MH12 CD 5678",
    },
    {
      listingId: listings[4].id,
      driverId: neha.id,
      hostId: priya.id,
      startDate: new Date("2026-04-01T00:00:00"),
      endDate: new Date("2026-04-30T23:59:00"),
      pricingType: "monthly",
      totalPrice: "7500",
      status: "completed",
      qrCode: `PARKBNB-${listings[4].id}-1711929600`,
      vehicleType: "Hatchback",
      vehiclePlate: "DL05 EF 9012",
    },
  ]);

  console.log("Seeding reviews...");
  await db.insert(reviewsTable).values([
    {
      listingId: listings[0].id,
      reviewerId: arjun.id,
      hostId: rahul.id,
      rating: 5,
      comment: "Bahut acha spot hai! BKC ke liye perfect. QR code entry smooth tha. Definitely booking again.",
    },
    {
      listingId: listings[2].id,
      reviewerId: arjun.id,
      hostId: neha.id,
      rating: 5,
      comment: "Great location in CP. Very safe, good lighting. Neha was very helpful on WhatsApp. Highly recommend.",
    },
    {
      listingId: listings[4].id,
      reviewerId: neha.id,
      hostId: priya.id,
      rating: 5,
      comment: "Used for a whole month for my Koramangala office commute. The EV charging was a huge bonus. Worth every rupee!",
    },
    {
      listingId: listings[7].id,
      reviewerId: arjun.id,
      hostId: vikram.id,
      rating: 4,
      comment: "Very professional facility. Clean, covered, and easy to access. Slightly far from the main entrance but good value for Hitech City area.",
    },
  ]);

  console.log("India seed complete! Users:", 5, "| Listings:", listings.length);
}

seed().catch(e => {
  console.error(e);
  process.exit(1);
});
